### ISSUE TITLE
Doc | Unity Pair Programming

### ISSUE THREAD

**Issue by A4Michael** [anarolon/person-and-ghost#10]
- [x] Research for tools inside Unity to facilitate pair programming
- [x] Research for tools inside Visual Studio to facilitate pair programming
- [x] If a tool was found:
   - [x] Make sure it is completely free
   - [x] Check if it allows for seamless collaboration 
   - [x] Document your findings
### Velocity = 1

**Comment by anarolon** [comment]
Sources: 

1. [https://raygun.com/blog/remote-pair-programming/](url)
