### ISSUE TITLE
DES | Choose Asset Pack(s) for Environment

### ISSUE THREAD

**Issue by anarolon** [anarolon/person-and-ghost#105]
- [x] Includes assets for floors and walls
- [x] Includes assets for game objects such as chest, collectables, torches, etc.
- [x] Document packs
- https://assetstore.unity.com/packages/2d/textures-materials/tiles/pixel-2d-castle-tileset-135397
- https://assetstore.unity.com/packages/2d/environments/platformer-set-150023
- https://assetstore.unity.com/packages/2d/environments/pixel-dark-forest-136825

**Comment by A4Michael** [comment]
After going over the free assets in the unity asset store and the ones presented by the team, I was not able to make a decision on the asset pack on my own because I will need the team input to decide the precise style of the assets we will introduce to the game.
