### ISSUE TITLE
Doc | Research Multiplayer Game Development in Unity

### ISSUE THREAD

**Issue by A4Michael** [anarolon/person-and-ghost#15]
# Local Multiplayer
- [x] How it is done?
- [x] What are the best practices?
- [x] Do a simple project showcasing what you learned
- [x] Take notes for future reference
### Velocity = 1

**Comment by anarolon** [comment]
Currently exploring the documentation available here [https://docs.unity3d.com/Manual/UNet.html](url). It seems that the current technology to implement Networking into a project is MLAPI and it's under development here [https://docs-multiplayer.unity3d.com/docs/getting-started/about-mlapi](url)

**Comment by anarolon** [comment]
### Local Multiplayer using the Input Action package
1. Add the Input Action package through the Package Manager window.
2. Create a new Input Action inside of the Assets folder.
3. Add a Control Scheme for a device, add the device to the list. For example, name the control scheme "Keyboard' and add Keyboard to the list by clicking on the "+" symbol.
3. Create an Action Map.
4. Add actions to the Action Map. For example, create an action called movement and add a 2D Vector Composite binding. You can rename the binding to "WASD".
5. Map the Up, Down, Left, and Right to a corresponding path in the controller you will use (Keyboard, Xbox controller, etc.)
6. For the second player, add a new Control Scheme.
