### ISSUE TITLE
Dev | Integrate Cinemachine to the Project

### ISSUE THREAD

**Issue by YenielDiaz** [anarolon/person-and-ghost#36]
- [x] Experiment with Cinemachine functionality
- [x] Integrate basic camera to follow players around

**Comment by A4Michael** [comment]
A bug was found where the script did not found Person in the scene on Start and had to found it in the FixedUpdate. This bug appear and later disappear, and now it reappear without changing code. To solve this a try and catch with a global flag was used to try to found it in Start (exactly the same code as for GhostMovement) and a catch to delegate this task to the FixedUpdate until it is found there. Another idea was to use an Invoke and when it was found stop the invoke but that idea was never tried.
