### ISSUE TITLE
Bug | Enemy State Machine does not reach Possessed State when changing states in StartLoop Coroutine

### ISSUE THREAD

**Issue by anarolon** [anarolon/person-and-ghost#38]
- This behavior was observed for the AIBigBoy enemy. It alternates between an Idle state and a MoveX state.
- Sometimes when trying to possess it, it keeps alternating between states as if the call to change the state to possession is replaced by another call to change to either of the main states (Idle or MoveX).

**Comment by jeanrodriguez27** [comment]
Bug fixed. Solution involved tweaking the AI's State Loop to force it to check if the AI is in a possessed state before loop-related state changes occur.
