### ISSUE TITLE
Doc | Complete GDD

### ISSUE THREAD

**Issue by anarolon** [anarolon/person-and-ghost#6]
- [x] Title Page
- [x] Game Overview
   - [x] Game Concept
   - [x] Genre 
   - [x] Target Audience
   - [x] Game Flow Summary
   - [x] Look and Feel
- [x] Gameplay and Mechanics
   - [x] Gameplay
   - [x] Mechanics
      - [x] Physics
      - [x] Movement in the game
      - [x] Objects
      - [x] Actions
      - [x] Combat
      - [x] Economy
      - [x] Screen Flow
   - [x] Game Options
   - [x] Replaying and Saving
   - [x] Cheats and Easter Eggs
- [x] Story, Setting and Characters
   - [x] Story and Narrative
   - [x] Game World
   - [x] Characters
- [x] Levels
   - [x] Levels
   - [x] Training Level
- [x] Interface
   - [x]  Visual System (HUD, Menus, Camera Model)
   - [x] Control System
   - [x] Audio, Music, Sound Effect
   - [x] Help System
- [x] AI
   - [x] Opponent and Enemy AI
   - [x] Non-Combat and NPCs
   - [x] Support AI
- [x] Technical
   - [x] Target Hardware
   - [x] Development hardware and software, Game Engine
   - [x] Network requirements
- [x] Game Art
### Velocity = 19

**Comment by A4Michael** [comment]
- [ ] Work on Screen Flow
