### ISSUE TITLE
Doc | Prototyping

### ISSUE THREAD

**Issue by anarolon** [anarolon/person-and-ghost#9]
- Are there any features inside of Unity that facilitate prototyping?
### Velocity = 1

**Comment by YenielDiaz** [comment]
Aside from free Assets in the Asset Store or external websites like kenney.nl the only thing I found was the BOLT visual scripting tool.
It seemed like it could work as a quick way to set up behavior when prototyping, but I found it to be too time consuming to get used to how to implement basic features. If we already know how to implement basic behavior with regular code, I believe it is better to just stick with that.
So for now:
- [ ] Free Assets
- [ ] Bolt
